export const sneakersData = [
  {
    id: 1,
    imageUrl: '/src/assets/sneakers/sneakers-1.jpg',
    title: 'Мужские Кроссовки Under Armour Curry 8',
    price: 15199,
    isAdded: false,
    isFavorite: false,
  },
  {
    id: 2,
    imageUrl: '/src/assets/sneakers/sneakers-2.jpg',
    title: 'Мужские Кроссовки Nike Blazer Mid Suede',
    price: 8499,
    isAdded: false,
    isFavorite: true,
  },
  {
    id: 3,
    imageUrl: '/src/assets/sneakers/sneakers-3.jpg',
    title: 'Мужские Кроссовки Puma X-Ray',
    price: 9999,
    isAdded: true,
    isFavorite: false,
  },
  {
    id: 4,
    imageUrl: '/src/assets/sneakers/sneakers-4.jpg',
    title: 'Мужские Кроссовки Reebok Classic',
    price: 7699,
    isAdded: true,
    isFavorite: true,
  },
  {
    id: 5,
    imageUrl: '/src/assets/sneakers/sneakers-5.jpg',
    title: 'Мужские Кроссовки Adidas Superstar',
    price: 8999,
    isAdded: false,
    isFavorite: false,
  },
  {
    id: 6,
    imageUrl: '/src/assets/sneakers/sneakers-6.jpg',
    title: 'Мужские Кроссовки New Balance 574',
    price: 10999,
    isAdded: false,
    isFavorite: true,
  },
  {
    id: 7,
    imageUrl: '/src/assets/sneakers/sneakers-7.jpg',
    title: 'Мужские Кроссовки ASICS Gel-Lyte III',
    price: 11999,
    isAdded: true,
    isFavorite: false,
  },
  {
    id: 8,
    imageUrl: '/src/assets/sneakers/sneakers-8.jpg',
    title: 'Мужские Кроссовки Converse Chuck Taylor',
    price: 6999,
    isAdded: true,
    isFavorite: true,
  },
  {
    id: 9,
    imageUrl: '/src/assets/sneakers/sneakers-9.jpg',
    title: 'Мужские Кроссовки Jordan 1 Retro High',
    price: 15999,
    isAdded: false,
    isFavorite: false,
  },
  {
    id: 10,
    imageUrl: '/src/assets/sneakers/sneakers-10.jpg',
    title: 'Мужские Кроссовки Vans Old Skool',
    price: 7499,
    isAdded: false,
    isFavorite: true,
  },
  {
    id: 11,
    imageUrl: '/src/assets/sneakers/sneakers-11.jpg',
    title: 'Мужские Кроссовки Fila Disruptor II',
    price: 8299,
    isAdded: true,
    isFavorite: false,
  },
  {
    id: 12,
    imageUrl: '/src/assets/sneakers/sneakers-12.jpg',
    title: 'Мужские Кроссовки Salomon Speedcross 5',
    price: 13499,
    isAdded: true,
    isFavorite: true,
  },
]
